use_gpu: true

data:
    sr: 16000
    shift_ms: 10
    fftl: 1024
    num_mels: 80
    hop_length: 160
    top_db: 120
    train_test_frac: 0.9
    word_occurance_threshold: 20
    num_test_utts_per_class: 100
    num_val_utts_per_class: 50
    num_augment_examples: 600

directories:
    coswara_root: /home/john/Documents/School/Spring_2021/Coswara-Data/Extracted_data/
    dicova_root: /home/john/Documents/School/Spring_2021/DiCOVA_Train_Val_Data_Release_updated/
    freesound_root: /home/john/Documents/School/Spring_2021/FSDKaggle2018AudioDataset/
    coughvid_root: /home/john/Documents/School/Spring_2021/COUGHVID/public_dataset/
    freesound_logspect_feats: freesound_logspect_feats/
    dicova_wavs: dicova_wavs/
    coughvid_wavs: coughvid_wavs/
    coughvid_logspect_feats: coughvid_logspect_feats/
    dicova_logspect_feats: dicova_logspect_feats/
    dicova_augmented_feats: dicova_augmented_feats/
    dicova_opensmile_feats: dicova_opensmile_feats/
    opensmile_feats: opensmile_feats/
    features: features/
    exps: exps/
    dicova_test_root: /home/john/Documents/School/Spring_2021/DiCOVA_Track_1_Evaluation_Release/
    dicova_test_wavs: dicova_test_wavs/
    dicova_test_logspect_feats: dicova_test_logspect_feats/
    dataloader_temp_wavs: dataloader_temp_wavs/

model:
    name: PostPreTrainClassifier
    batch_first: true
    dropout: 0.0
    lr: 0.00001
    output_dim: 100
    incorrect_scaler: 15

train:
    log_step: 100
    model_save_step: 500
    num_epochs: 700
    batch_size: 3
    specaugment: true
    specaug_probability: 0.0

pretraining:
    future_frames: 10
    hidden_size: 400
    linear_hidden_size: 500
    encoder_num_layers: 4
    batch_first: true
    dropout: 0.1
    lr: 0.00005

pretraining2:
    future_frames: 10
    hidden_size: 400
    linear_hidden_size: 500
    encoder1_num_layers: 2
    encoder2_num_layers: 2
    batch_first: true
    dropout: 0.1
    lr: 0.0001

post_pretraining_classifier:
    lr: 0.0001
    hidden_size: 200
    linear_hidden_size: 300
    encoder_num_layers: 2
    batch_first: true
    dropout: 0.1
    opensmile_dropout: 0.1
    bidirectional: true
    incorrect_scaler: 15
    deep_F_beta: 0.7