use_gpu: true

data:
    sr: 16000
    shift_ms: 10
    fftl: 1024
    num_mels: 80
    hop_length: 160
    top_db: 120
    train_test_frac: 0.9
    word_occurance_threshold: 20
    num_test_utts_per_class: 100
    num_val_utts_per_class: 50

directories:
    coswara_root: /home/john/Documents/School/Spring_2021/Coswara-Data/Extracted_data/
    dicova_root: /home/john/Documents/School/Spring_2021/DiCOVA_Train_Val_Data_Release/
    freesound_root: /home/john/Documents/School/Spring_2021/FSDKaggle2018AudioDataset/
    freesound_logspect_feats: freesound_logspect_feats/
    dicova_wavs: wavs/
    opensmile_feats: opensmile_feats/
    features: features/
    exps: exps/

model:
    name: PreTrainer
    batch_first: true
    dropout: 0.0
    lr: 0.00001
    output_dim: 100
    incorrect_scaler: 15

train:
    log_step: 100
    model_save_step: 2000
    num_epochs: 30000
    batch_size: 3

pretraining:
    future_frames: 3
    hidden_size: 400
    linear_hidden_size: 500
    encoder_num_layers: 4
    batch_first: true
    dropout: 0.1
    lr: 0.00005